export const countryCodes: Record<string, string> = {
    Afghanistan	:"af",    
    Albania	:"al",
    Algeria	:"dz",
    Andorra	:"ad",
    Angola	:"ao",
    Argentina	:"ar",
    Armenia	:"am",
    Australia	:"au",
    Austria	:"at",
    Azerbaijan	:"az",
    Bahamas	:"bs",
    Bahrain	:"bh",
    Bangladesh	:"bd",
    Barbados	:"bb",
    Belarus	:"by",
    Belgium	:"be",
    Belize	:"bz",
    Benin	:"bj",
    Bermuda	:"bm",
    Bhutan	:"bt",
    Bolivia	:"bo",
    "Bosnia And Herzegovina"	:"ba",
    Botswana	:"bw",
    Brazil	:"br",
    Brunei	:"bn",
    Bulgaria	:"bg",
    "Burkina fasco"	:"bf",
    Burundi	:"bi",
    Cambodia	:"kh",
    Cameroon	:"cm",
    Canada	:"ca",
    "Cape Verde"	:"cv",
    "Cayman Islands"	:"ky",
    "Central African Republic"	:"cf",
    Chad	:"td",
    Chile	:"cl",
    China	:"cn",
    Colombia	:"co",
    Comoros	:"km",
    Congo	:"cg",
    "Cook islands"	:"ck",
    "Costa Rica"	:"cr",
    Croatia	:"hr",
    Cuba	:"cu",
    Curaçao	:"cw",
    Cyprus	:"cy",
    "Czech republic"	:"cz",
    Denmark	:"dk",
    Djibouti	:"dj",
    Dominica	:"dm",
    "Dominican republic"	:"do",
    "DR Congo"	:"cd",
    Ecuador	:"ec",
    Egypt	:"eg",
    "El Salvador"	:"sv",
    "Equatorial Guinea"	:"gq",
    Eritrea	:"er",
    Estonia	:"ee",
    Eswatini	:"sz",
    Ethiopia	:"et",
    Fiji	:"fj",
    Finland	:"fi",
    France	:"fr",
    "French polynesia"	:"pf",
    Gabon	:"ga",
    Gambia	:"gm",
    Georgia	:"ge",
    Germany	:"de",
    Ghana	:"gh",
    Gibraltar	:"gi",
    Greece	:"gr",
    Grenada	:"gd",
    Guatemala	:"gt",
    Guinea	:"gn",
    Guyana	:"gy",
    Haiti	:"ht",
    Honduras	:"hn",
    "Hong kong"	:"hk",
    Hungary	:"hu",
    Iceland	:"is",
    India	:"in",
    Indonesia	:"id",
    Iran	:"ir",
    Iraq	:"iq",
    Ireland	:"ie",
    Israel	:"il",
    Italy	:"it",
    "Ivory Coast"	:"ci",
    Kazakhstan	:"kz",
    Kenya	:"ke",
    Kiribati	:"ki",
    Kosovo	:"xk",
    Kuwait	:"kw",
    Kyrgyzstan	:"kg",
    Laos	:"la",
    Latvia	:"lv",
    Lebanon	:"lb",
    Lesotho	:"ls",
    Liberia	:"lr",
    Libya	:"ly",
    Liechtenstein	:"li",
    Lithuania	:"lt",
    Luxembourg	:"lu",
    Macau	:"mo",
    Macedonia	:"mk",
    Madagascar	:"mg",
    Malawi	:"mw",
    Malaysia	:"my",
    Maldives	:"mv",
    Mali	:"ml",
    Malta	:"mt",
    "Marshall Islands"	:"mh",
    Mauritania	:"mr",
    Mauritius	:"mu",
    Mexico	:"mx",
    Micronesia	:"fm",
    Moldova	:"md",
    Monaco	:"mc",
    Mongolia	:"mn",
    Montenegro	:"me",
    Morocco	:"ma",
    Mozambique	:"mz",
    Myanmar	:"mm",
    Namibia	:"na",
    Nauru	:"nr",
    Nepal	:"np",
    Netherland	:"nl",
    "New caledonia"	:"nc",
    "New zealand"	:"nz",
    Nicaragua	:"ni",
    Niger	:"ne",
    Nigeria	:"ng",
    "North korea"	:"kp",
    Norway	:"no",
    Oman	:"om",
    Pakistan	:"pk",
    Palau	:"pw",
    Palestine	:"ps",
    Panama	:"pa",
    "Papua New Guinea"	:"pg",
    Paraguay	:"py",
    Peru	:"pe",
    Philippines	:"ph",
    Poland	:"pl",
    Portugal	:"pt",
    "Puerto rico"	:"pr",
    Qatar	:"qa",
    Romania	:"ro",
    Russia	:"ru",
    Rwanda	:"rw",
    "Saint lucia"	:"lc",
    "Saint martin(dutch)"	:"sx",
    Samoa	:"ws",
    "San Marino"	:"sm",
    "Sao tome and principe"	:"st",
    "Saudi arabia"	:"sa",
    Senegal	:"sn",
    Serbia	:"rs",
    Seychelles	:"sc",
    "Sierra Leone"	:"sl",
    Singapore	:"sg",
    Slovakia	:"sk",
    Slovenia	:"si",
    "Solomon Islands"	:"sb",
    Somalia	:"so",
    "South africa"	:"za",
    "South korea"	:"kr",
    Spain	:"es",
    "Sri Lanka"	:"lk",
    Sudan	:"sd",
    Suriname	:"sr",
    Sweden	:"se",
    Switzerland	:"ch",
    Syria	:"sy",
    Taiwan	:"tw",
    Tajikistan	:"tj",
    Tanzania	:"tz",
    Thailand	:"th",
    "Timor-Leste"	:"tl",
    Togo	:"tg",
    Tonga	:"to",
    "Trinidad and tobago"	:"tt",
    Tunisia	:"tn",
    Turkey	:"tr",
    Turkmenistan	:"tm",
    Tuvalu	:"tv",
    Uganda	:"ug",
    Ukraine	:"ua",
    "United arab emirates"	:"ae",
    "United kingdom"	:"gb",
    "United states of america"	:"us",
    Uruguay	:"uy",
    Uzbekistan	:"uz",
    Vanuatu	:"vu",
    Vatican	:"va",
    Venezuela	:"ve",
    Vietnam	:"vi",
    "Virgin Islands (British)"	:"vg",
    World	:"wo",
    Yemen	:"ye",
    Zambia	:"zm",
    Zimbabwe	:"zw"
}


export const categories: Record<string, string> = {
    business: "Business",
    crime: "Crime",
    domestic: "Domestic",
    education: "Education",
    entertainment: "Entertainment",
    environment: "Environment",
    food: "Food",
    health: "Health",
    lifestyle: "Lifestyle",
    other: "Other",
    politics: "Politics",
    science: "Science",
    sports: "Sports",
    technology: "Technology",
    top: "Top",
    tourism: "Tourism",
    world: "World"
}   
